# Generated by Django 2.1.7 on 2019-03-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=148)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
